// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	Commentor string             `json:"commentor"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// cab be negative or positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LikeWithPost struct {
	Username string `json:"username"`
	PostID   int64  `json:"post_id"`
}

type Order struct {
	ID           int64              `json:"id"`
	ProductID    int64              `json:"product_id"`
	Buyer        string             `json:"buyer"`
	Quantity     int64              `json:"quantity"`
	PriceAtOrder int64              `json:"price_at_order"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID        int64              `json:"id"`
	Author    string             `json:"author"`
	ProductID pgtype.Int8        `json:"product_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Media     []string           `json:"media"`
	Location  pgtype.Text        `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          int64       `json:"id"`
	Seller      string      `json:"seller"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Price       int64       `json:"price"`
	Stock       int64       `json:"stock"`
	Images      []string    `json:"images"`
}

type Review struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	Reviewer  string             `json:"reviewer"`
	Rating    int32              `json:"rating"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Username          string             `json:"username"`
	Password          string             `json:"password"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Location          pgtype.Text        `json:"location"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WishWithProduct struct {
	Username  string `json:"username"`
	ProductID int64  `json:"product_id"`
}
