// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: search.sql

package db

import (
	"context"
)

const createSearchCount = `-- name: CreateSearchCount :exec
INSERT INTO search_count (search_text) VALUES ($1)
`

func (q *Queries) CreateSearchCount(ctx context.Context, searchText string) error {
	_, err := q.db.Exec(ctx, createSearchCount, searchText)
	return err
}

const getSearchCount = `-- name: GetSearchCount :exec
SELECT count FROM search_count WHERE search_text = $1
`

func (q *Queries) GetSearchCount(ctx context.Context, searchText string) error {
	_, err := q.db.Exec(ctx, getSearchCount, searchText)
	return err
}

const increceSearchCount = `-- name: IncreceSearchCount :exec
UPDATE search_count SET count = count + 1 WHERE search_text = $1
`

func (q *Queries) IncreceSearchCount(ctx context.Context, searchText string) error {
	_, err := q.db.Exec(ctx, increceSearchCount, searchText)
	return err
}
